# Generated by Django 2.2.4 on 2019-09-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_auto_20190830_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='what_to_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentfortask', to='tasker.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished',
            field=models.DateTimeField(),
        ),
    ]
