# Generated by Django 2.2.4 on 2019-09-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_auto_20190904_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='what_to_comment',
            new_name='whatcommented',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commented',
            new_name='whencommented',
        ),
    ]
