# Generated by Django 2.2.4 on 2019-09-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0004_auto_20190904_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentator',
            new_name='creator',
        ),
    ]
